// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.2
// source: api/v1/card.proto

package card

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NomenclatureId uint64                 `protobuf:"varint,1,opt,name=nomenclatureId,proto3" json:"nomenclatureId,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Sku            string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity       int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SizeId         uint64                 `protobuf:"varint,6,opt,name=sizeId,proto3" json:"sizeId,omitempty"`
	Barcode        string                 `protobuf:"bytes,7,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_api_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCardRequest) GetNomenclatureId() uint64 {
	if x != nil {
		return x.NomenclatureId
	}
	return 0
}

func (x *CreateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCardRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateCardRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateCardRequest) GetSizeId() uint64 {
	if x != nil {
		return x.SizeId
	}
	return 0
}

func (x *CreateCardRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CardData              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_api_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardResponse) GetData() *CardData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCardsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsListRequest) Reset() {
	*x = GetCardsListRequest{}
	mi := &file_api_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsListRequest) ProtoMessage() {}

func (x *GetCardsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsListRequest.ProtoReflect.Descriptor instead.
func (*GetCardsListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_card_proto_rawDescGZIP(), []int{2}
}

type CardData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NomenclatureId uint64                 `protobuf:"varint,2,opt,name=nomenclatureId,proto3" json:"nomenclatureId,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Sku            string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity       int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SizeId         uint64                 `protobuf:"varint,7,opt,name=sizeId,proto3" json:"sizeId,omitempty"`
	Barcode        string                 `protobuf:"bytes,8,opt,name=barcode,proto3" json:"barcode,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CardData) Reset() {
	*x = CardData{}
	mi := &file_api_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardData) ProtoMessage() {}

func (x *CardData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardData.ProtoReflect.Descriptor instead.
func (*CardData) Descriptor() ([]byte, []int) {
	return file_api_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *CardData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardData) GetNomenclatureId() uint64 {
	if x != nil {
		return x.NomenclatureId
	}
	return 0
}

func (x *CardData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CardData) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CardData) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CardData) GetSizeId() uint64 {
	if x != nil {
		return x.SizeId
	}
	return 0
}

func (x *CardData) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CardData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CardData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetCardsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*CardData            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsListResponse) Reset() {
	*x = GetCardsListResponse{}
	mi := &file_api_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsListResponse) ProtoMessage() {}

func (x *GetCardsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsListResponse.ProtoReflect.Descriptor instead.
func (*GetCardsListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardsListResponse) GetData() []*CardData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_v1_card_proto protoreflect.FileDescriptor

const file_api_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/card.proto\x12&github.com.mrbeaver1.tshirts_back.card\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x11CreateCardRequest\x12&\n" +
	"\x0enomenclatureId\x18\x01 \x01(\x04R\x0enomenclatureId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x16\n" +
	"\x06sizeId\x18\x06 \x01(\x04R\x06sizeId\x12\x18\n" +
	"\abarcode\x18\a \x01(\tR\abarcode\"Z\n" +
	"\x12CreateCardResponse\x12D\n" +
	"\x04data\x18\x01 \x01(\v20.github.com.mrbeaver1.tshirts_back.card.CardDataR\x04data\"\x15\n" +
	"\x13GetCardsListRequest\"\x96\x02\n" +
	"\bCardData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12&\n" +
	"\x0enomenclatureId\x18\x02 \x01(\x04R\x0enomenclatureId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12\x16\n" +
	"\x06sizeId\x18\a \x01(\x04R\x06sizeId\x12\x18\n" +
	"\abarcode\x18\b \x01(\tR\abarcode\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\n" +
	" \x01(\tR\tupdatedAt\"\\\n" +
	"\x14GetCardsListResponse\x12D\n" +
	"\x04data\x18\x01 \x03(\v20.github.com.mrbeaver1.tshirts_back.card.CardDataR\x04data2\xce\x02\n" +
	"\vCardService\x12\x9c\x01\n" +
	"\n" +
	"CreateCard\x129.github.com.mrbeaver1.tshirts_back.card.CreateCardRequest\x1a:.github.com.mrbeaver1.tshirts_back.card.CreateCardResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/card\x12\x9f\x01\n" +
	"\fGetCardsList\x12;.github.com.mrbeaver1.tshirts_back.card.GetCardsListRequest\x1a<.github.com.mrbeaver1.tshirts_back.card.GetCardsListResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/cardB5Z3github.com/mrbeaver1/tshirts_back/pkg/api/card;cardb\x06proto3"

var (
	file_api_v1_card_proto_rawDescOnce sync.Once
	file_api_v1_card_proto_rawDescData []byte
)

func file_api_v1_card_proto_rawDescGZIP() []byte {
	file_api_v1_card_proto_rawDescOnce.Do(func() {
		file_api_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_card_proto_rawDesc), len(file_api_v1_card_proto_rawDesc)))
	})
	return file_api_v1_card_proto_rawDescData
}

var file_api_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_card_proto_goTypes = []any{
	(*CreateCardRequest)(nil),    // 0: github.com.mrbeaver1.tshirts_back.card.CreateCardRequest
	(*CreateCardResponse)(nil),   // 1: github.com.mrbeaver1.tshirts_back.card.CreateCardResponse
	(*GetCardsListRequest)(nil),  // 2: github.com.mrbeaver1.tshirts_back.card.GetCardsListRequest
	(*CardData)(nil),             // 3: github.com.mrbeaver1.tshirts_back.card.CardData
	(*GetCardsListResponse)(nil), // 4: github.com.mrbeaver1.tshirts_back.card.GetCardsListResponse
}
var file_api_v1_card_proto_depIdxs = []int32{
	3, // 0: github.com.mrbeaver1.tshirts_back.card.CreateCardResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.card.CardData
	3, // 1: github.com.mrbeaver1.tshirts_back.card.GetCardsListResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.card.CardData
	0, // 2: github.com.mrbeaver1.tshirts_back.card.CardService.CreateCard:input_type -> github.com.mrbeaver1.tshirts_back.card.CreateCardRequest
	2, // 3: github.com.mrbeaver1.tshirts_back.card.CardService.GetCardsList:input_type -> github.com.mrbeaver1.tshirts_back.card.GetCardsListRequest
	1, // 4: github.com.mrbeaver1.tshirts_back.card.CardService.CreateCard:output_type -> github.com.mrbeaver1.tshirts_back.card.CreateCardResponse
	4, // 5: github.com.mrbeaver1.tshirts_back.card.CardService.GetCardsList:output_type -> github.com.mrbeaver1.tshirts_back.card.GetCardsListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_card_proto_init() }
func file_api_v1_card_proto_init() {
	if File_api_v1_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_card_proto_rawDesc), len(file_api_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_card_proto_goTypes,
		DependencyIndexes: file_api_v1_card_proto_depIdxs,
		MessageInfos:      file_api_v1_card_proto_msgTypes,
	}.Build()
	File_api_v1_card_proto = out.File
	file_api_v1_card_proto_goTypes = nil
	file_api_v1_card_proto_depIdxs = nil
}
