// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: api/v1/color.proto

package color

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ColorService_CreateColor_FullMethodName   = "/github.com.mrbeaver1.tshirts_back.color.ColorService/CreateColor"
	ColorService_GetColorsList_FullMethodName = "/github.com.mrbeaver1.tshirts_back.color.ColorService/GetColorsList"
)

// ColorServiceClient is the client API for ColorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ColorServiceClient interface {
	CreateColor(ctx context.Context, in *CreateColorRequest, opts ...grpc.CallOption) (*CreateColorResponse, error)
	GetColorsList(ctx context.Context, in *GetColorsListRequest, opts ...grpc.CallOption) (*GetColorsListResponse, error)
}

type colorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewColorServiceClient(cc grpc.ClientConnInterface) ColorServiceClient {
	return &colorServiceClient{cc}
}

func (c *colorServiceClient) CreateColor(ctx context.Context, in *CreateColorRequest, opts ...grpc.CallOption) (*CreateColorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateColorResponse)
	err := c.cc.Invoke(ctx, ColorService_CreateColor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colorServiceClient) GetColorsList(ctx context.Context, in *GetColorsListRequest, opts ...grpc.CallOption) (*GetColorsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetColorsListResponse)
	err := c.cc.Invoke(ctx, ColorService_GetColorsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColorServiceServer is the server API for ColorService service.
// All implementations must embed UnimplementedColorServiceServer
// for forward compatibility.
type ColorServiceServer interface {
	CreateColor(context.Context, *CreateColorRequest) (*CreateColorResponse, error)
	GetColorsList(context.Context, *GetColorsListRequest) (*GetColorsListResponse, error)
	mustEmbedUnimplementedColorServiceServer()
}

// UnimplementedColorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedColorServiceServer struct{}

func (UnimplementedColorServiceServer) CreateColor(context.Context, *CreateColorRequest) (*CreateColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateColor not implemented")
}
func (UnimplementedColorServiceServer) GetColorsList(context.Context, *GetColorsListRequest) (*GetColorsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetColorsList not implemented")
}
func (UnimplementedColorServiceServer) mustEmbedUnimplementedColorServiceServer() {}
func (UnimplementedColorServiceServer) testEmbeddedByValue()                      {}

// UnsafeColorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ColorServiceServer will
// result in compilation errors.
type UnsafeColorServiceServer interface {
	mustEmbedUnimplementedColorServiceServer()
}

func RegisterColorServiceServer(s grpc.ServiceRegistrar, srv ColorServiceServer) {
	// If the following call pancis, it indicates UnimplementedColorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ColorService_ServiceDesc, srv)
}

func _ColorService_CreateColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).CreateColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColorService_CreateColor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).CreateColor(ctx, req.(*CreateColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColorService_GetColorsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetColorsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorServiceServer).GetColorsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColorService_GetColorsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorServiceServer).GetColorsList(ctx, req.(*GetColorsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ColorService_ServiceDesc is the grpc.ServiceDesc for ColorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ColorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.mrbeaver1.tshirts_back.color.ColorService",
	HandlerType: (*ColorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateColor",
			Handler:    _ColorService_CreateColor_Handler,
		},
		{
			MethodName: "GetColorsList",
			Handler:    _ColorService_GetColorsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/color.proto",
}
