// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.2
// source: api/v1/color.proto

package color

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hex           string                 `protobuf:"bytes,2,opt,name=hex,proto3" json:"hex,omitempty"`
	Rgb           string                 `protobuf:"bytes,3,opt,name=rgb,proto3" json:"rgb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColorRequest) Reset() {
	*x = CreateColorRequest{}
	mi := &file_api_v1_color_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColorRequest) ProtoMessage() {}

func (x *CreateColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_color_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColorRequest.ProtoReflect.Descriptor instead.
func (*CreateColorRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_color_proto_rawDescGZIP(), []int{0}
}

func (x *CreateColorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateColorRequest) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

func (x *CreateColorRequest) GetRgb() string {
	if x != nil {
		return x.Rgb
	}
	return ""
}

type CreateColorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ColorData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColorResponse) Reset() {
	*x = CreateColorResponse{}
	mi := &file_api_v1_color_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColorResponse) ProtoMessage() {}

func (x *CreateColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_color_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColorResponse.ProtoReflect.Descriptor instead.
func (*CreateColorResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_color_proto_rawDescGZIP(), []int{1}
}

func (x *CreateColorResponse) GetData() *ColorData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetColorsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColorsListRequest) Reset() {
	*x = GetColorsListRequest{}
	mi := &file_api_v1_color_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColorsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorsListRequest) ProtoMessage() {}

func (x *GetColorsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_color_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorsListRequest.ProtoReflect.Descriptor instead.
func (*GetColorsListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_color_proto_rawDescGZIP(), []int{2}
}

type ColorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hex           string                 `protobuf:"bytes,3,opt,name=hex,proto3" json:"hex,omitempty"`
	Rgb           string                 `protobuf:"bytes,4,opt,name=rgb,proto3" json:"rgb,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorData) Reset() {
	*x = ColorData{}
	mi := &file_api_v1_color_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorData) ProtoMessage() {}

func (x *ColorData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_color_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorData.ProtoReflect.Descriptor instead.
func (*ColorData) Descriptor() ([]byte, []int) {
	return file_api_v1_color_proto_rawDescGZIP(), []int{3}
}

func (x *ColorData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ColorData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColorData) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

func (x *ColorData) GetRgb() string {
	if x != nil {
		return x.Rgb
	}
	return ""
}

func (x *ColorData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ColorData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetColorsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ColorData           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColorsListResponse) Reset() {
	*x = GetColorsListResponse{}
	mi := &file_api_v1_color_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColorsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColorsListResponse) ProtoMessage() {}

func (x *GetColorsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_color_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColorsListResponse.ProtoReflect.Descriptor instead.
func (*GetColorsListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_color_proto_rawDescGZIP(), []int{4}
}

func (x *GetColorsListResponse) GetData() []*ColorData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_v1_color_proto protoreflect.FileDescriptor

const file_api_v1_color_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/color.proto\x12'github.com.mrbeaver1.tshirts_back.color\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x12CreateColorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03hex\x18\x02 \x01(\tR\x03hex\x12\x10\n" +
	"\x03rgb\x18\x03 \x01(\tR\x03rgb\"]\n" +
	"\x13CreateColorResponse\x12F\n" +
	"\x04data\x18\x01 \x01(\v22.github.com.mrbeaver1.tshirts_back.color.ColorDataR\x04data\"\x16\n" +
	"\x14GetColorsListRequest\"\x8f\x01\n" +
	"\tColorData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03hex\x18\x03 \x01(\tR\x03hex\x12\x10\n" +
	"\x03rgb\x18\x04 \x01(\tR\x03rgb\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"_\n" +
	"\x15GetColorsListResponse\x12F\n" +
	"\x04data\x18\x01 \x03(\v22.github.com.mrbeaver1.tshirts_back.color.ColorDataR\x04data2\xdb\x02\n" +
	"\fColorService\x12\xa2\x01\n" +
	"\vCreateColor\x12;.github.com.mrbeaver1.tshirts_back.color.CreateColorRequest\x1a<.github.com.mrbeaver1.tshirts_back.color.CreateColorResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/color\x12\xa5\x01\n" +
	"\rGetColorsList\x12=.github.com.mrbeaver1.tshirts_back.color.GetColorsListRequest\x1a>.github.com.mrbeaver1.tshirts_back.color.GetColorsListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/colorB7Z5github.com/mrbeaver1/tshirts_back/pkg/api/color;colorb\x06proto3"

var (
	file_api_v1_color_proto_rawDescOnce sync.Once
	file_api_v1_color_proto_rawDescData []byte
)

func file_api_v1_color_proto_rawDescGZIP() []byte {
	file_api_v1_color_proto_rawDescOnce.Do(func() {
		file_api_v1_color_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_color_proto_rawDesc), len(file_api_v1_color_proto_rawDesc)))
	})
	return file_api_v1_color_proto_rawDescData
}

var file_api_v1_color_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_color_proto_goTypes = []any{
	(*CreateColorRequest)(nil),    // 0: github.com.mrbeaver1.tshirts_back.color.CreateColorRequest
	(*CreateColorResponse)(nil),   // 1: github.com.mrbeaver1.tshirts_back.color.CreateColorResponse
	(*GetColorsListRequest)(nil),  // 2: github.com.mrbeaver1.tshirts_back.color.GetColorsListRequest
	(*ColorData)(nil),             // 3: github.com.mrbeaver1.tshirts_back.color.ColorData
	(*GetColorsListResponse)(nil), // 4: github.com.mrbeaver1.tshirts_back.color.GetColorsListResponse
}
var file_api_v1_color_proto_depIdxs = []int32{
	3, // 0: github.com.mrbeaver1.tshirts_back.color.CreateColorResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.color.ColorData
	3, // 1: github.com.mrbeaver1.tshirts_back.color.GetColorsListResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.color.ColorData
	0, // 2: github.com.mrbeaver1.tshirts_back.color.ColorService.CreateColor:input_type -> github.com.mrbeaver1.tshirts_back.color.CreateColorRequest
	2, // 3: github.com.mrbeaver1.tshirts_back.color.ColorService.GetColorsList:input_type -> github.com.mrbeaver1.tshirts_back.color.GetColorsListRequest
	1, // 4: github.com.mrbeaver1.tshirts_back.color.ColorService.CreateColor:output_type -> github.com.mrbeaver1.tshirts_back.color.CreateColorResponse
	4, // 5: github.com.mrbeaver1.tshirts_back.color.ColorService.GetColorsList:output_type -> github.com.mrbeaver1.tshirts_back.color.GetColorsListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_color_proto_init() }
func file_api_v1_color_proto_init() {
	if File_api_v1_color_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_color_proto_rawDesc), len(file_api_v1_color_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_color_proto_goTypes,
		DependencyIndexes: file_api_v1_color_proto_depIdxs,
		MessageInfos:      file_api_v1_color_proto_msgTypes,
	}.Build()
	File_api_v1_color_proto = out.File
	file_api_v1_color_proto_goTypes = nil
	file_api_v1_color_proto_depIdxs = nil
}
