// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: api/v1/nomenclature.proto

package nomenclature

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NomenclatureService_CreateNomenclature_FullMethodName = "/github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureService/CreateNomenclature"
	NomenclatureService_GetLeadsList_FullMethodName       = "/github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureService/GetLeadsList"
)

// NomenclatureServiceClient is the client API for NomenclatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NomenclatureServiceClient interface {
	CreateNomenclature(ctx context.Context, in *CreateNomenclatureRequest, opts ...grpc.CallOption) (*CreateNomenclatureResponse, error)
	GetLeadsList(ctx context.Context, in *GetNomenclatureListRequest, opts ...grpc.CallOption) (*GetNomenclatureListResponse, error)
}

type nomenclatureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNomenclatureServiceClient(cc grpc.ClientConnInterface) NomenclatureServiceClient {
	return &nomenclatureServiceClient{cc}
}

func (c *nomenclatureServiceClient) CreateNomenclature(ctx context.Context, in *CreateNomenclatureRequest, opts ...grpc.CallOption) (*CreateNomenclatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNomenclatureResponse)
	err := c.cc.Invoke(ctx, NomenclatureService_CreateNomenclature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nomenclatureServiceClient) GetLeadsList(ctx context.Context, in *GetNomenclatureListRequest, opts ...grpc.CallOption) (*GetNomenclatureListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNomenclatureListResponse)
	err := c.cc.Invoke(ctx, NomenclatureService_GetLeadsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NomenclatureServiceServer is the server API for NomenclatureService service.
// All implementations must embed UnimplementedNomenclatureServiceServer
// for forward compatibility.
type NomenclatureServiceServer interface {
	CreateNomenclature(context.Context, *CreateNomenclatureRequest) (*CreateNomenclatureResponse, error)
	GetLeadsList(context.Context, *GetNomenclatureListRequest) (*GetNomenclatureListResponse, error)
	mustEmbedUnimplementedNomenclatureServiceServer()
}

// UnimplementedNomenclatureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNomenclatureServiceServer struct{}

func (UnimplementedNomenclatureServiceServer) CreateNomenclature(context.Context, *CreateNomenclatureRequest) (*CreateNomenclatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNomenclature not implemented")
}
func (UnimplementedNomenclatureServiceServer) GetLeadsList(context.Context, *GetNomenclatureListRequest) (*GetNomenclatureListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeadsList not implemented")
}
func (UnimplementedNomenclatureServiceServer) mustEmbedUnimplementedNomenclatureServiceServer() {}
func (UnimplementedNomenclatureServiceServer) testEmbeddedByValue()                             {}

// UnsafeNomenclatureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NomenclatureServiceServer will
// result in compilation errors.
type UnsafeNomenclatureServiceServer interface {
	mustEmbedUnimplementedNomenclatureServiceServer()
}

func RegisterNomenclatureServiceServer(s grpc.ServiceRegistrar, srv NomenclatureServiceServer) {
	// If the following call pancis, it indicates UnimplementedNomenclatureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NomenclatureService_ServiceDesc, srv)
}

func _NomenclatureService_CreateNomenclature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNomenclatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomenclatureServiceServer).CreateNomenclature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomenclatureService_CreateNomenclature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomenclatureServiceServer).CreateNomenclature(ctx, req.(*CreateNomenclatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NomenclatureService_GetLeadsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNomenclatureListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomenclatureServiceServer).GetLeadsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NomenclatureService_GetLeadsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomenclatureServiceServer).GetLeadsList(ctx, req.(*GetNomenclatureListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NomenclatureService_ServiceDesc is the grpc.ServiceDesc for NomenclatureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NomenclatureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureService",
	HandlerType: (*NomenclatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNomenclature",
			Handler:    _NomenclatureService_CreateNomenclature_Handler,
		},
		{
			MethodName: "GetLeadsList",
			Handler:    _NomenclatureService_GetLeadsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/nomenclature.proto",
}
