// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.2
// source: api/v1/nomenclature.proto

package nomenclature

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNomenclatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNomenclatureRequest) Reset() {
	*x = CreateNomenclatureRequest{}
	mi := &file_api_v1_nomenclature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNomenclatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNomenclatureRequest) ProtoMessage() {}

func (x *CreateNomenclatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nomenclature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNomenclatureRequest.ProtoReflect.Descriptor instead.
func (*CreateNomenclatureRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nomenclature_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNomenclatureRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateNomenclatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *NomenclatureData      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNomenclatureResponse) Reset() {
	*x = CreateNomenclatureResponse{}
	mi := &file_api_v1_nomenclature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNomenclatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNomenclatureResponse) ProtoMessage() {}

func (x *CreateNomenclatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nomenclature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNomenclatureResponse.ProtoReflect.Descriptor instead.
func (*CreateNomenclatureResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_nomenclature_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNomenclatureResponse) GetData() *NomenclatureData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetNomenclatureListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNomenclatureListRequest) Reset() {
	*x = GetNomenclatureListRequest{}
	mi := &file_api_v1_nomenclature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNomenclatureListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNomenclatureListRequest) ProtoMessage() {}

func (x *GetNomenclatureListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nomenclature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNomenclatureListRequest.ProtoReflect.Descriptor instead.
func (*GetNomenclatureListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nomenclature_proto_rawDescGZIP(), []int{2}
}

type NomenclatureData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Color         uint64                 `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Status        uint64                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NomenclatureData) Reset() {
	*x = NomenclatureData{}
	mi := &file_api_v1_nomenclature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NomenclatureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NomenclatureData) ProtoMessage() {}

func (x *NomenclatureData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nomenclature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NomenclatureData.ProtoReflect.Descriptor instead.
func (*NomenclatureData) Descriptor() ([]byte, []int) {
	return file_api_v1_nomenclature_proto_rawDescGZIP(), []int{3}
}

func (x *NomenclatureData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NomenclatureData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NomenclatureData) GetColor() uint64 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *NomenclatureData) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NomenclatureData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NomenclatureData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetNomenclatureListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*NomenclatureData    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNomenclatureListResponse) Reset() {
	*x = GetNomenclatureListResponse{}
	mi := &file_api_v1_nomenclature_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNomenclatureListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNomenclatureListResponse) ProtoMessage() {}

func (x *GetNomenclatureListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nomenclature_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNomenclatureListResponse.ProtoReflect.Descriptor instead.
func (*GetNomenclatureListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_nomenclature_proto_rawDescGZIP(), []int{4}
}

func (x *GetNomenclatureListResponse) GetData() []*NomenclatureData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_v1_nomenclature_proto protoreflect.FileDescriptor

const file_api_v1_nomenclature_proto_rawDesc = "" +
	"\n" +
	"\x19api/v1/nomenclature.proto\x12.github.com.mrbeaver1.tshirts_back.nomenclature\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x19CreateNomenclatureRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"r\n" +
	"\x1aCreateNomenclatureResponse\x12T\n" +
	"\x04data\x18\x01 \x01(\v2@.github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureDataR\x04data\"\x1c\n" +
	"\x1aGetNomenclatureListRequest\"\xa2\x01\n" +
	"\x10NomenclatureData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05color\x18\x03 \x01(\x04R\x05color\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x04R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"s\n" +
	"\x1bGetNomenclatureListResponse\x12T\n" +
	"\x04data\x18\x01 \x03(\v2@.github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureDataR\x04data2\xac\x03\n" +
	"\x13NomenclatureService\x12\xcc\x01\n" +
	"\x12CreateNomenclature\x12I.github.com.mrbeaver1.tshirts_back.nomenclature.CreateNomenclatureRequest\x1aJ.github.com.mrbeaver1.tshirts_back.nomenclature.CreateNomenclatureResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/nomenclature\x12\xc5\x01\n" +
	"\fGetLeadsList\x12J.github.com.mrbeaver1.tshirts_back.nomenclature.GetNomenclatureListRequest\x1aK.github.com.mrbeaver1.tshirts_back.nomenclature.GetNomenclatureListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/nomenclatureBEZCgithub.com/mrbeaver1/tshirts_back/pkg/api/nomenclature;nomenclatureb\x06proto3"

var (
	file_api_v1_nomenclature_proto_rawDescOnce sync.Once
	file_api_v1_nomenclature_proto_rawDescData []byte
)

func file_api_v1_nomenclature_proto_rawDescGZIP() []byte {
	file_api_v1_nomenclature_proto_rawDescOnce.Do(func() {
		file_api_v1_nomenclature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_nomenclature_proto_rawDesc), len(file_api_v1_nomenclature_proto_rawDesc)))
	})
	return file_api_v1_nomenclature_proto_rawDescData
}

var file_api_v1_nomenclature_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_nomenclature_proto_goTypes = []any{
	(*CreateNomenclatureRequest)(nil),   // 0: github.com.mrbeaver1.tshirts_back.nomenclature.CreateNomenclatureRequest
	(*CreateNomenclatureResponse)(nil),  // 1: github.com.mrbeaver1.tshirts_back.nomenclature.CreateNomenclatureResponse
	(*GetNomenclatureListRequest)(nil),  // 2: github.com.mrbeaver1.tshirts_back.nomenclature.GetNomenclatureListRequest
	(*NomenclatureData)(nil),            // 3: github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureData
	(*GetNomenclatureListResponse)(nil), // 4: github.com.mrbeaver1.tshirts_back.nomenclature.GetNomenclatureListResponse
}
var file_api_v1_nomenclature_proto_depIdxs = []int32{
	3, // 0: github.com.mrbeaver1.tshirts_back.nomenclature.CreateNomenclatureResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureData
	3, // 1: github.com.mrbeaver1.tshirts_back.nomenclature.GetNomenclatureListResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureData
	0, // 2: github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureService.CreateNomenclature:input_type -> github.com.mrbeaver1.tshirts_back.nomenclature.CreateNomenclatureRequest
	2, // 3: github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureService.GetLeadsList:input_type -> github.com.mrbeaver1.tshirts_back.nomenclature.GetNomenclatureListRequest
	1, // 4: github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureService.CreateNomenclature:output_type -> github.com.mrbeaver1.tshirts_back.nomenclature.CreateNomenclatureResponse
	4, // 5: github.com.mrbeaver1.tshirts_back.nomenclature.NomenclatureService.GetLeadsList:output_type -> github.com.mrbeaver1.tshirts_back.nomenclature.GetNomenclatureListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_nomenclature_proto_init() }
func file_api_v1_nomenclature_proto_init() {
	if File_api_v1_nomenclature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_nomenclature_proto_rawDesc), len(file_api_v1_nomenclature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_nomenclature_proto_goTypes,
		DependencyIndexes: file_api_v1_nomenclature_proto_depIdxs,
		MessageInfos:      file_api_v1_nomenclature_proto_msgTypes,
	}.Build()
	File_api_v1_nomenclature_proto = out.File
	file_api_v1_nomenclature_proto_goTypes = nil
	file_api_v1_nomenclature_proto_depIdxs = nil
}
