// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: api/v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for GetProducts
type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_api_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{0}
}

// Response message for GetProducts
type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_api_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_api_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// Request message for GetProduct
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response message for GetProduct
type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_api_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetData) Reset() {
	*x = GetData{}
	mi := &file_api_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetData) ProtoMessage() {}

func (x *GetData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetData.ProtoReflect.Descriptor instead.
func (*GetData) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetData) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Request message for CreateProduct
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_api_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Response message for CreateProduct
type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_api_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateData) Reset() {
	*x = CreateData{}
	mi := &file_api_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateData) ProtoMessage() {}

func (x *CreateData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateData.ProtoReflect.Descriptor instead.
func (*CreateData) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *CreateData) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Request message for UpdateProduct
type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_api_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Response message for UpdateProduct
type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_api_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateData) Reset() {
	*x = UpdateData{}
	mi := &file_api_v1_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateData) ProtoMessage() {}

func (x *UpdateData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateData.ProtoReflect.Descriptor instead.
func (*UpdateData) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateData) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// Request message for DeleteProduct
type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_api_v1_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response message for DeleteProduct
type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_api_v1_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteProductResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteData) Reset() {
	*x = DeleteData{}
	mi := &file_api_v1_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteData) ProtoMessage() {}

func (x *DeleteData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteData.ProtoReflect.Descriptor instead.
func (*DeleteData) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Product represents a product entity
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ColorId       uint64                 `protobuf:"varint,3,opt,name=color_id,json=colorId,proto3" json:"color_id,omitempty"`
	SizeId        uint64                 `protobuf:"varint,4,opt,name=size_id,json=sizeId,proto3" json:"size_id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Available     uint64                 `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	ParentId      *uint64                `protobuf:"varint,7,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_v1_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_v1_product_proto_rawDescGZIP(), []int{15}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetColorId() uint64 {
	if x != nil {
		return x.ColorId
	}
	return 0
}

func (x *Product) GetSizeId() uint64 {
	if x != nil {
		return x.SizeId
	}
	return 0
}

func (x *Product) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *Product) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_api_v1_product_proto protoreflect.FileDescriptor

const file_api_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/product.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n" +
	"\x12GetProductsRequest\"7\n" +
	"\x13GetProductsResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.api.v1.DataR\x04data\"3\n" +
	"\x04Data\x12+\n" +
	"\bproducts\x18\x01 \x03(\v2\x0f.api.v1.ProductR\bproducts\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"6\n" +
	"\x12GetProductResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.api.v1.DataR\x04data\"4\n" +
	"\aGetData\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"A\n" +
	"\x14CreateProductRequest\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"9\n" +
	"\x15CreateProductResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.api.v1.DataR\x04data\"7\n" +
	"\n" +
	"CreateData\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"A\n" +
	"\x14UpdateProductRequest\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"9\n" +
	"\x15UpdateProductResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.api.v1.DataR\x04data\"7\n" +
	"\n" +
	"UpdateData\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"9\n" +
	"\x15DeleteProductResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.api.v1.DataR\x04data\"&\n" +
	"\n" +
	"DeleteData\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x90\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bcolor_id\x18\x03 \x01(\x04R\acolorId\x12\x17\n" +
	"\asize_id\x18\x04 \x01(\x04R\x06sizeId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x04R\bquantity\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\x04R\tavailable\x12 \n" +
	"\tparent_id\x18\a \x01(\x04H\x00R\bparentId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_deleted_at2\x9e\x04\n" +
	"\x0eProductService\x12\\\n" +
	"\vGetProducts\x12\x1a.api.v1.GetProductsRequest\x1a\x1b.api.v1.GetProductsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/products\x12^\n" +
	"\n" +
	"GetProduct\x12\x19.api.v1.GetProductRequest\x1a\x1a.api.v1.GetProductResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/products/{id}\x12k\n" +
	"\rCreateProduct\x12\x1c.api.v1.CreateProductRequest\x1a\x1d.api.v1.CreateProductResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\aproduct\"\f/v1/products\x12x\n" +
	"\rUpdateProduct\x12\x1c.api.v1.UpdateProductRequest\x1a\x1d.api.v1.UpdateProductResponse\"*\x82\xd3\xe4\x93\x02$:\aproduct\x1a\x19/v1/products/{product.id}\x12g\n" +
	"\rDeleteProduct\x12\x1c.api.v1.DeleteProductRequest\x1a\x1d.api.v1.DeleteProductResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/products/{id}B1Z/github.com/mrbeaver1/tshirts_back/pkg/api/v1;v1b\x06proto3"

var (
	file_api_v1_product_proto_rawDescOnce sync.Once
	file_api_v1_product_proto_rawDescData []byte
)

func file_api_v1_product_proto_rawDescGZIP() []byte {
	file_api_v1_product_proto_rawDescOnce.Do(func() {
		file_api_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_product_proto_rawDesc), len(file_api_v1_product_proto_rawDesc)))
	})
	return file_api_v1_product_proto_rawDescData
}

var file_api_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_v1_product_proto_goTypes = []any{
	(*GetProductsRequest)(nil),    // 0: api.v1.GetProductsRequest
	(*GetProductsResponse)(nil),   // 1: api.v1.GetProductsResponse
	(*Data)(nil),                  // 2: api.v1.Data
	(*GetProductRequest)(nil),     // 3: api.v1.GetProductRequest
	(*GetProductResponse)(nil),    // 4: api.v1.GetProductResponse
	(*GetData)(nil),               // 5: api.v1.GetData
	(*CreateProductRequest)(nil),  // 6: api.v1.CreateProductRequest
	(*CreateProductResponse)(nil), // 7: api.v1.CreateProductResponse
	(*CreateData)(nil),            // 8: api.v1.CreateData
	(*UpdateProductRequest)(nil),  // 9: api.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil), // 10: api.v1.UpdateProductResponse
	(*UpdateData)(nil),            // 11: api.v1.UpdateData
	(*DeleteProductRequest)(nil),  // 12: api.v1.DeleteProductRequest
	(*DeleteProductResponse)(nil), // 13: api.v1.DeleteProductResponse
	(*DeleteData)(nil),            // 14: api.v1.DeleteData
	(*Product)(nil),               // 15: api.v1.Product
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_api_v1_product_proto_depIdxs = []int32{
	2,  // 0: api.v1.GetProductsResponse.data:type_name -> api.v1.Data
	15, // 1: api.v1.Data.products:type_name -> api.v1.Product
	2,  // 2: api.v1.GetProductResponse.data:type_name -> api.v1.Data
	15, // 3: api.v1.GetData.product:type_name -> api.v1.Product
	15, // 4: api.v1.CreateProductRequest.product:type_name -> api.v1.Product
	2,  // 5: api.v1.CreateProductResponse.data:type_name -> api.v1.Data
	15, // 6: api.v1.CreateData.product:type_name -> api.v1.Product
	15, // 7: api.v1.UpdateProductRequest.product:type_name -> api.v1.Product
	2,  // 8: api.v1.UpdateProductResponse.data:type_name -> api.v1.Data
	15, // 9: api.v1.UpdateData.product:type_name -> api.v1.Product
	2,  // 10: api.v1.DeleteProductResponse.data:type_name -> api.v1.Data
	16, // 11: api.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	16, // 12: api.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	16, // 13: api.v1.Product.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 14: api.v1.ProductService.GetProducts:input_type -> api.v1.GetProductsRequest
	3,  // 15: api.v1.ProductService.GetProduct:input_type -> api.v1.GetProductRequest
	6,  // 16: api.v1.ProductService.CreateProduct:input_type -> api.v1.CreateProductRequest
	9,  // 17: api.v1.ProductService.UpdateProduct:input_type -> api.v1.UpdateProductRequest
	12, // 18: api.v1.ProductService.DeleteProduct:input_type -> api.v1.DeleteProductRequest
	1,  // 19: api.v1.ProductService.GetProducts:output_type -> api.v1.GetProductsResponse
	4,  // 20: api.v1.ProductService.GetProduct:output_type -> api.v1.GetProductResponse
	7,  // 21: api.v1.ProductService.CreateProduct:output_type -> api.v1.CreateProductResponse
	10, // 22: api.v1.ProductService.UpdateProduct:output_type -> api.v1.UpdateProductResponse
	13, // 23: api.v1.ProductService.DeleteProduct:output_type -> api.v1.DeleteProductResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_v1_product_proto_init() }
func file_api_v1_product_proto_init() {
	if File_api_v1_product_proto != nil {
		return
	}
	file_api_v1_product_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_product_proto_rawDesc), len(file_api_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_product_proto_goTypes,
		DependencyIndexes: file_api_v1_product_proto_depIdxs,
		MessageInfos:      file_api_v1_product_proto_msgTypes,
	}.Build()
	File_api_v1_product_proto = out.File
	file_api_v1_product_proto_goTypes = nil
	file_api_v1_product_proto_depIdxs = nil
}
