// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.2
// source: api/v1/size.proto

package size

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSizeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RussianStandard       uint64                 `protobuf:"varint,1,opt,name=russianStandard,proto3" json:"russianStandard,omitempty"`
	InternationalStandard string                 `protobuf:"bytes,2,opt,name=internationalStandard,proto3" json:"internationalStandard,omitempty"`
	Dimensions            *SizeDimensions        `protobuf:"bytes,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateSizeRequest) Reset() {
	*x = CreateSizeRequest{}
	mi := &file_api_v1_size_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSizeRequest) ProtoMessage() {}

func (x *CreateSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_size_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSizeRequest.ProtoReflect.Descriptor instead.
func (*CreateSizeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_size_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSizeRequest) GetRussianStandard() uint64 {
	if x != nil {
		return x.RussianStandard
	}
	return 0
}

func (x *CreateSizeRequest) GetInternationalStandard() string {
	if x != nil {
		return x.InternationalStandard
	}
	return ""
}

func (x *CreateSizeRequest) GetDimensions() *SizeDimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type CreateSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SizeData              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSizeResponse) Reset() {
	*x = CreateSizeResponse{}
	mi := &file_api_v1_size_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSizeResponse) ProtoMessage() {}

func (x *CreateSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_size_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSizeResponse.ProtoReflect.Descriptor instead.
func (*CreateSizeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_size_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSizeResponse) GetData() *SizeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSizesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizesListRequest) Reset() {
	*x = GetSizesListRequest{}
	mi := &file_api_v1_size_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizesListRequest) ProtoMessage() {}

func (x *GetSizesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_size_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizesListRequest.ProtoReflect.Descriptor instead.
func (*GetSizesListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_size_proto_rawDescGZIP(), []int{2}
}

type SizeData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RussianStandard       uint64                 `protobuf:"varint,2,opt,name=russianStandard,proto3" json:"russianStandard,omitempty"`
	InternationalStandard string                 `protobuf:"bytes,3,opt,name=internationalStandard,proto3" json:"internationalStandard,omitempty"`
	Dimensions            *SizeDimensions        `protobuf:"bytes,4,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt             string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SizeData) Reset() {
	*x = SizeData{}
	mi := &file_api_v1_size_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeData) ProtoMessage() {}

func (x *SizeData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_size_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeData.ProtoReflect.Descriptor instead.
func (*SizeData) Descriptor() ([]byte, []int) {
	return file_api_v1_size_proto_rawDescGZIP(), []int{3}
}

func (x *SizeData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SizeData) GetRussianStandard() uint64 {
	if x != nil {
		return x.RussianStandard
	}
	return 0
}

func (x *SizeData) GetInternationalStandard() string {
	if x != nil {
		return x.InternationalStandard
	}
	return ""
}

func (x *SizeData) GetDimensions() *SizeDimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *SizeData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SizeData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSizesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SizeData            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizesListResponse) Reset() {
	*x = GetSizesListResponse{}
	mi := &file_api_v1_size_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizesListResponse) ProtoMessage() {}

func (x *GetSizesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_size_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizesListResponse.ProtoReflect.Descriptor instead.
func (*GetSizesListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_size_proto_rawDescGZIP(), []int{4}
}

func (x *GetSizesListResponse) GetData() []*SizeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SizeDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint64                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeDimensions) Reset() {
	*x = SizeDimensions{}
	mi := &file_api_v1_size_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeDimensions) ProtoMessage() {}

func (x *SizeDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_size_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeDimensions.ProtoReflect.Descriptor instead.
func (*SizeDimensions) Descriptor() ([]byte, []int) {
	return file_api_v1_size_proto_rawDescGZIP(), []int{5}
}

func (x *SizeDimensions) GetWidth() uint64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SizeDimensions) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_api_v1_size_proto protoreflect.FileDescriptor

const file_api_v1_size_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/size.proto\x12&github.com.mrbeaver1.tshirts_back.size\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n" +
	"\x11CreateSizeRequest\x12(\n" +
	"\x0frussianStandard\x18\x01 \x01(\x04R\x0frussianStandard\x124\n" +
	"\x15internationalStandard\x18\x02 \x01(\tR\x15internationalStandard\x12V\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\v26.github.com.mrbeaver1.tshirts_back.size.SizeDimensionsR\n" +
	"dimensions\"Z\n" +
	"\x12CreateSizeResponse\x12D\n" +
	"\x04data\x18\x01 \x01(\v20.github.com.mrbeaver1.tshirts_back.size.SizeDataR\x04data\"\x15\n" +
	"\x13GetSizesListRequest\"\x8e\x02\n" +
	"\bSizeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12(\n" +
	"\x0frussianStandard\x18\x02 \x01(\x04R\x0frussianStandard\x124\n" +
	"\x15internationalStandard\x18\x03 \x01(\tR\x15internationalStandard\x12V\n" +
	"\n" +
	"dimensions\x18\x04 \x01(\v26.github.com.mrbeaver1.tshirts_back.size.SizeDimensionsR\n" +
	"dimensions\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"\\\n" +
	"\x14GetSizesListResponse\x12D\n" +
	"\x04data\x18\x01 \x03(\v20.github.com.mrbeaver1.tshirts_back.size.SizeDataR\x04data\">\n" +
	"\x0eSizeDimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x04R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height2\xce\x02\n" +
	"\vSizeService\x12\x9c\x01\n" +
	"\n" +
	"CreateSize\x129.github.com.mrbeaver1.tshirts_back.size.CreateSizeRequest\x1a:.github.com.mrbeaver1.tshirts_back.size.CreateSizeResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/size\x12\x9f\x01\n" +
	"\fGetSizesList\x12;.github.com.mrbeaver1.tshirts_back.size.GetSizesListRequest\x1a<.github.com.mrbeaver1.tshirts_back.size.GetSizesListResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/sizeB5Z3github.com/mrbeaver1/tshirts_back/pkg/api/size;sizeb\x06proto3"

var (
	file_api_v1_size_proto_rawDescOnce sync.Once
	file_api_v1_size_proto_rawDescData []byte
)

func file_api_v1_size_proto_rawDescGZIP() []byte {
	file_api_v1_size_proto_rawDescOnce.Do(func() {
		file_api_v1_size_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_size_proto_rawDesc), len(file_api_v1_size_proto_rawDesc)))
	})
	return file_api_v1_size_proto_rawDescData
}

var file_api_v1_size_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_size_proto_goTypes = []any{
	(*CreateSizeRequest)(nil),    // 0: github.com.mrbeaver1.tshirts_back.size.CreateSizeRequest
	(*CreateSizeResponse)(nil),   // 1: github.com.mrbeaver1.tshirts_back.size.CreateSizeResponse
	(*GetSizesListRequest)(nil),  // 2: github.com.mrbeaver1.tshirts_back.size.GetSizesListRequest
	(*SizeData)(nil),             // 3: github.com.mrbeaver1.tshirts_back.size.SizeData
	(*GetSizesListResponse)(nil), // 4: github.com.mrbeaver1.tshirts_back.size.GetSizesListResponse
	(*SizeDimensions)(nil),       // 5: github.com.mrbeaver1.tshirts_back.size.SizeDimensions
}
var file_api_v1_size_proto_depIdxs = []int32{
	5, // 0: github.com.mrbeaver1.tshirts_back.size.CreateSizeRequest.dimensions:type_name -> github.com.mrbeaver1.tshirts_back.size.SizeDimensions
	3, // 1: github.com.mrbeaver1.tshirts_back.size.CreateSizeResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.size.SizeData
	5, // 2: github.com.mrbeaver1.tshirts_back.size.SizeData.dimensions:type_name -> github.com.mrbeaver1.tshirts_back.size.SizeDimensions
	3, // 3: github.com.mrbeaver1.tshirts_back.size.GetSizesListResponse.data:type_name -> github.com.mrbeaver1.tshirts_back.size.SizeData
	0, // 4: github.com.mrbeaver1.tshirts_back.size.SizeService.CreateSize:input_type -> github.com.mrbeaver1.tshirts_back.size.CreateSizeRequest
	2, // 5: github.com.mrbeaver1.tshirts_back.size.SizeService.GetSizesList:input_type -> github.com.mrbeaver1.tshirts_back.size.GetSizesListRequest
	1, // 6: github.com.mrbeaver1.tshirts_back.size.SizeService.CreateSize:output_type -> github.com.mrbeaver1.tshirts_back.size.CreateSizeResponse
	4, // 7: github.com.mrbeaver1.tshirts_back.size.SizeService.GetSizesList:output_type -> github.com.mrbeaver1.tshirts_back.size.GetSizesListResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_size_proto_init() }
func file_api_v1_size_proto_init() {
	if File_api_v1_size_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_size_proto_rawDesc), len(file_api_v1_size_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_size_proto_goTypes,
		DependencyIndexes: file_api_v1_size_proto_depIdxs,
		MessageInfos:      file_api_v1_size_proto_msgTypes,
	}.Build()
	File_api_v1_size_proto = out.File
	file_api_v1_size_proto_goTypes = nil
	file_api_v1_size_proto_depIdxs = nil
}
