// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: api/v1/size.proto

package size

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SizeService_CreateSize_FullMethodName   = "/github.com.mrbeaver1.tshirts_back.size.SizeService/CreateSize"
	SizeService_GetSizesList_FullMethodName = "/github.com.mrbeaver1.tshirts_back.size.SizeService/GetSizesList"
)

// SizeServiceClient is the client API for SizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SizeServiceClient interface {
	CreateSize(ctx context.Context, in *CreateSizeRequest, opts ...grpc.CallOption) (*CreateSizeResponse, error)
	GetSizesList(ctx context.Context, in *GetSizesListRequest, opts ...grpc.CallOption) (*GetSizesListResponse, error)
}

type sizeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSizeServiceClient(cc grpc.ClientConnInterface) SizeServiceClient {
	return &sizeServiceClient{cc}
}

func (c *sizeServiceClient) CreateSize(ctx context.Context, in *CreateSizeRequest, opts ...grpc.CallOption) (*CreateSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSizeResponse)
	err := c.cc.Invoke(ctx, SizeService_CreateSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) GetSizesList(ctx context.Context, in *GetSizesListRequest, opts ...grpc.CallOption) (*GetSizesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSizesListResponse)
	err := c.cc.Invoke(ctx, SizeService_GetSizesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SizeServiceServer is the server API for SizeService service.
// All implementations must embed UnimplementedSizeServiceServer
// for forward compatibility.
type SizeServiceServer interface {
	CreateSize(context.Context, *CreateSizeRequest) (*CreateSizeResponse, error)
	GetSizesList(context.Context, *GetSizesListRequest) (*GetSizesListResponse, error)
	mustEmbedUnimplementedSizeServiceServer()
}

// UnimplementedSizeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSizeServiceServer struct{}

func (UnimplementedSizeServiceServer) CreateSize(context.Context, *CreateSizeRequest) (*CreateSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSize not implemented")
}
func (UnimplementedSizeServiceServer) GetSizesList(context.Context, *GetSizesListRequest) (*GetSizesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSizesList not implemented")
}
func (UnimplementedSizeServiceServer) mustEmbedUnimplementedSizeServiceServer() {}
func (UnimplementedSizeServiceServer) testEmbeddedByValue()                     {}

// UnsafeSizeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SizeServiceServer will
// result in compilation errors.
type UnsafeSizeServiceServer interface {
	mustEmbedUnimplementedSizeServiceServer()
}

func RegisterSizeServiceServer(s grpc.ServiceRegistrar, srv SizeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSizeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SizeService_ServiceDesc, srv)
}

func _SizeService_CreateSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).CreateSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SizeService_CreateSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).CreateSize(ctx, req.(*CreateSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_GetSizesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSizesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).GetSizesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SizeService_GetSizesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).GetSizesList(ctx, req.(*GetSizesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SizeService_ServiceDesc is the grpc.ServiceDesc for SizeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SizeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.mrbeaver1.tshirts_back.size.SizeService",
	HandlerType: (*SizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSize",
			Handler:    _SizeService_CreateSize_Handler,
		},
		{
			MethodName: "GetSizesList",
			Handler:    _SizeService_GetSizesList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/size.proto",
}
